// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Yqetwkprs_yme2YDAq2ZGcAL1QMRZY8',
    appId: '1:319868585793:web:2e598925561658449f43c0',
    messagingSenderId: '319868585793',
    projectId: 'smart-board-9c23c',
    authDomain: 'smart-board-9c23c.firebaseapp.com',
    storageBucket: 'smart-board-9c23c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYqa9KlZqHc1C4BqnYAIOOx56dQ7EHcB4',
    appId: '1:319868585793:android:01fdf906db23f5fd9f43c0',
    messagingSenderId: '319868585793',
    projectId: 'smart-board-9c23c',
    storageBucket: 'smart-board-9c23c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhVoFOqauVx_R9elmgla0Cl-PsjcJhCHQ',
    appId: '1:319868585793:ios:9d7c5a4c2d6bef389f43c0',
    messagingSenderId: '319868585793',
    projectId: 'smart-board-9c23c',
    storageBucket: 'smart-board-9c23c.appspot.com',
    iosBundleId: 'com.example.smartboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhVoFOqauVx_R9elmgla0Cl-PsjcJhCHQ',
    appId: '1:319868585793:ios:9d7c5a4c2d6bef389f43c0',
    messagingSenderId: '319868585793',
    projectId: 'smart-board-9c23c',
    storageBucket: 'smart-board-9c23c.appspot.com',
    iosBundleId: 'com.example.smartboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4Yqetwkprs_yme2YDAq2ZGcAL1QMRZY8',
    appId: '1:319868585793:web:8ff2a4aea27e27819f43c0',
    messagingSenderId: '319868585793',
    projectId: 'smart-board-9c23c',
    authDomain: 'smart-board-9c23c.firebaseapp.com',
    storageBucket: 'smart-board-9c23c.appspot.com',
  );
}
